# Generated by Django 2.2.1 on 2019-05-06 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATTSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('expired', 'Expired')], default='new', max_length=10)),
                ('device_id', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('phone_model', models.CharField(blank=True, default='', max_length=128)),
                ('network_type', models.CharField(blank=True, default='', max_length=5)),
                ('effective_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plans.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
