# Generated by Django 2.2.1 on 2020-06-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprint_subscriptions', '0001_initial'),
        ('att_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedVoiceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateField()),
                ('seconds_used', models.IntegerField()),
                ('att_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedDataUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateField()),
                ('kilobytes_used', models.IntegerField()),
                ('att_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aggregatedvoiceusage',
            constraint=models.UniqueConstraint(fields=('usage_date', 'att_subscription'), name='unique_voice_att_and_date'),
        ),
        migrations.AddConstraint(
            model_name='aggregatedvoiceusage',
            constraint=models.UniqueConstraint(fields=('usage_date', 'sprint_subscription'), name='unique_voice_sprint_and_date'),
        ),
        migrations.AddConstraint(
            model_name='aggregateddatausage',
            constraint=models.UniqueConstraint(fields=('usage_date', 'att_subscription'), name='unique_data_att_and_date'),
        ),
        migrations.AddConstraint(
            model_name='aggregateddatausage',
            constraint=models.UniqueConstraint(fields=('usage_date', 'sprint_subscription'), name='unique_data_sprint_and_date'),
        ),
    ]
