# Generated by Django 2.2.1 on 2020-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregated_usage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregateddatausage',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='aggregatedvoiceusage',
            name='amount',
        ),
        migrations.AddField(
            model_name='aggregateddatausage',
            name='total_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aggregatedvoiceusage',
            name='total_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
