# Generated by Django 3.0.1 on 2020-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregated_usage', '0003_auto_20200619_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateddatausage',
            name='kilobytes_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aggregatedvoiceusage',
            name='seconds_used',
            field=models.IntegerField(default=0),
        ),
    ]
