# Generated by Django 2.2.1 on 2020-05-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('att_subscriptions', '0001_initial'),
        ('sprint_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateTimeField(null=True)),
                ('seconds_used', models.IntegerField()),
                ('att_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
        ),
        migrations.CreateModel(
            name='DataUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateTimeField(null=True)),
                ('kilobytes_used', models.IntegerField()),
                ('att_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
        ),
    ]
