# Generated by Django 2.2.1 on 2020-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datausagerecord',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
