# Generated by Django 2.2.1 on 2020-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_auto_20200618_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datausagerecord',
            old_name='att_subscription_id',
            new_name='att_subscription',
        ),
        migrations.RenameField(
            model_name='datausagerecord',
            old_name='sprint_subscription_id',
            new_name='sprint_subscription',
        ),
        migrations.RenameField(
            model_name='voiceusagerecord',
            old_name='att_subscription_id',
            new_name='att_subscription',
        ),
        migrations.RenameField(
            model_name='voiceusagerecord',
            old_name='sprint_subscription_id',
            new_name='sprint_subscription',
        ),
        migrations.AlterField(
            model_name='voiceusagerecord',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
