# Generated by Django 2.2.1 on 2020-04-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_subscriptions', '0001_initial'),
        ('att_subscriptions', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='att_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sprint_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription'),
        ),
    ]
